// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChQyBmu2zo7cF3f8J5AiXI6kAA218s1s0',
    appId: '1:982109319751:web:aa3856561be9de43af3762',
    messagingSenderId: '982109319751',
    projectId: 'engineering-drawing-city-5dd6f',
    authDomain: 'engineering-drawing-city-5dd6f.firebaseapp.com',
    storageBucket: 'engineering-drawing-city-5dd6f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjOpQnXFF0YBSPrb0s2a7gWjch_kJAwuA',
    appId: '1:982109319751:android:461ec36d966099d0af3762',
    messagingSenderId: '982109319751',
    projectId: 'engineering-drawing-city-5dd6f',
    storageBucket: 'engineering-drawing-city-5dd6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCczCmRZd4kIcDsvLZK7XF8eDiU06QkyuY',
    appId: '1:982109319751:ios:6988e573a8730c03af3762',
    messagingSenderId: '982109319751',
    projectId: 'engineering-drawing-city-5dd6f',
    storageBucket: 'engineering-drawing-city-5dd6f.firebasestorage.app',
    iosBundleId: 'com.drawingcity.engineeringDrawingCity',
  );
}
